run:
  skip-files:
    - xxhash.go

issues:
  exclude-rules:
    - path: token.go
      linters:
        - errcheck
    - path: escape.go
      linters:
        - errcheck

    - linters:
        - typecheck
      text: "syscall/js"
    - linters:
        - staticcheck
      text: "SA9003"
    - linters:
        - typecheck
      text: "github.com/norunners/vert"