/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Result of compiling an Astro file. */
export declare class AstroCompileResult {
  /** The generated JavaScript code. */
  get code(): string
  /** Source map JSON string (empty until sourcemap support is implemented). */
  get map(): string
  /** CSS scope hash for the component. */
  get scope(): string
  /** Extracted CSS from `<style>` tags (empty until CSS support). */
  get css(): Array<string>
  /** Hoisted scripts extracted from the template. */
  get scripts(): Array<NapiHoistedScript>
  /** Components with `client:*` hydration directives (except `client:only`). */
  get hydratedComponents(): Array<NapiHydratedComponent>
  /** Components with `client:only` directive. */
  get clientOnlyComponents(): Array<NapiHydratedComponent>
  /** Components with `server:defer` directive. */
  get serverComponents(): Array<NapiHydratedComponent>
  /** Whether the template contains an explicit `<head>` element. */
  get containsHead(): boolean
  /** Whether the component propagates head content. */
  get propagation(): boolean
  /** Style processing errors (stub: always empty). */
  get styleError(): Array<string>
  /** Diagnostic messages (stub: always empty). */
  get diagnostics(): Array<string>
  /** Any compilation errors encountered (oxc-specific). */
  get errors(): Array<OxcError>
}

/**
 * Options for compiling Astro files to JavaScript.
 *
 * Matches the Go compiler's `TransformOptions` from `@astrojs/compiler`.
 * Some fields (such as `sourcemap`, `compact`, CSS scoping) are stubs accepted for API compatibility.
 */
export interface AstroCompileOptions {
  /**
   * The filename of the Astro component being compiled.
   * Used in the `$$createComponent` call for debugging.
   */
  filename?: string
  /**
   * A normalized version of the filename used for scope hash generation.
   * If not provided, falls back to `filename`.
   */
  normalizedFilename?: string
  /**
   * The import specifier for Astro runtime functions.
   * Defaults to `"astro/runtime/server/index.js"`.
   */
  internalUrl?: string
  /**
   * Whether to generate a source map.
   * **Stub**: not yet implemented.
   *
   * @default false
   */
  sourcemap?: boolean
  /**
   * Arguments passed to `$$createAstro` when the Astro global is used.
   * Defaults to `"https://astro.build"`.
   */
  astroGlobalArgs?: string
  /**
   * Whether to collapse whitespace in the HTML output.
   * **Stub**: not yet implemented.
   *
   * @default false
   */
  compact?: boolean
  /**
   * Enable scoped slot result handling.
   * When `true`, slot callbacks receive the `$$result` render context parameter.
   *
   * @default false
   */
  resultScopedSlot?: boolean
  /**
   * Strategy for CSS scoping: `"where"`, `"class"`, or `"attribute"`.
   * **Stub**: not yet implemented.
   *
   * @default "where"
   */
  scopedStyleStrategy?: string
  /**
   * URL for the view transitions animation CSS.
   * **Stub**: not yet implemented.
   */
  transitionsAnimationUrl?: string
  /**
   * Whether to annotate generated code with the source file path.
   * **Stub**: not yet implemented.
   *
   * @default false
   */
  annotateSourceFile?: boolean
  /**
   * Enable experimental script ordering behavior.
   * **Stub**: not yet implemented.
   *
   * @default false
   */
  experimentalScriptOrder?: boolean
  /**
   * Whether to strip HTML comments from component slot children.
   * Matches the official Astro compiler behavior by default.
   *
   * @default true
   */
  stripSlotComments?: boolean
  /**
   * Whether the caller has a `resolvePath` function.
   *
   * When `true`, the codegen will:
   * - Skip emitting `$$createMetadata` import
   * - Skip emitting `import * as $$moduleN` re-imports
   * - Skip emitting `export const $$metadata = ...`
   * - Use plain string literals instead of `$$metadata.resolvePath(...)`
   *
   * The actual path resolution is done by the JS wrapper layer using
   * the `resolvePath` callback post-compilation.
   *
   * @default false
   */
  resolvePathProvided?: boolean
}

/**
 * Compile Astro file to JavaScript asynchronously on a separate thread.
 *
 * This transforms an Astro file into JavaScript code compatible with the Astro runtime.
 * The output follows the same format as the official Astro compiler.
 *
 * Generally `compileAstroSync` is preferable to use as it does not have the overhead
 * of spawning a thread. If you need to parallelize compilation of multiple files,
 * it is recommended to use worker threads.
 *
 * @example
 * ```javascript
 * import { compileAstro } from '@astrojs/compiler';
 *
 * const result = await compileAstro(`---
 * const name = "World";
 * ---
 * <h1>Hello {name}!</h1>`, {
 *   filename: 'Component.astro',
 * });
 *
 * console.log(result.code); // Generated JavaScript
 * ```
 */
export declare function compileAstro(sourceText: string, options?: AstroCompileOptions | undefined | null): Promise<AstroCompileResult>

/**
 * Compile Astro file to JavaScript synchronously on current thread.
 *
 * This transforms an Astro file into JavaScript code compatible with the Astro runtime.
 * The output follows the same format as the official Astro compiler.
 *
 * @example
 * ```javascript
 * import { compileAstroSync } from '@astrojs/compiler';
 *
 * const result = compileAstroSync(`---
 * const name = "World";
 * ---
 * <h1>Hello {name}!</h1>`, {
 *   filename: 'Component.astro',
 * });
 *
 * console.log(result.code); // Generated JavaScript
 * ```
 */
export declare function compileAstroSync(sourceText: string, options?: AstroCompileOptions | undefined | null): AstroCompileResult

export interface ErrorLabel {
  message: string | null
  start: number
  end: number
}

/** A hoisted script extracted from an Astro component. */
export interface NapiHoistedScript {
  /** The script type: `"inline"` or `"external"`. */
  type: string
  /** The inline script code (when type is `"inline"`). */
  code?: string
  /** The external script src URL (when type is `"external"`). */
  src?: string
}

/** A hydrated component reference found in the template. */
export interface NapiHydratedComponent {
  /** The export name from the module (e.g., `"default"`). */
  exportName: string
  /** The local variable name used in the component. */
  localName: string
  /** The import specifier (e.g., `"../components/Counter.jsx"`). */
  specifier: string
  /** The resolved path (empty string if unresolved). */
  resolvedPath: string
}

export interface OxcError {
  severity: Severity
  message: string
  labels: Array<ErrorLabel>
  helpMessage: string | null
  codeframe: string | null
}

export declare const enum Severity {
  Error = 'Error',
  Warning = 'Warning',
  Advice = 'Advice'
}
